apiVersion: apps/v1
kind: Deployment
metadata:
  name: pawcare
spec:
  replicas: 2

  selector:
    matchLabels:
      app: pawcare

  template:
    metadata:
      labels:
        app: pawcare

    spec:
      containers:
        - name: pawcare
          image: kuki25/pawcare:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: pawcare-db-secrets
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: pawcare-db-secrets
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pawcare-db-secrets
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pawcare-db-secrets
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pawcare-db-secrets
                  key: DB_PASSWORD
            - name: DB_SSLMODE
              value: "require"